[package]
name = "{{project-name}}"
version = "0.1.0"
edition = "2024"
description = "{{description}}"
authors = ["{{authors}}"]

[dependencies]
agb = "0.22.5"

[profile.dev]
opt-level = 3
debug = true

[profile.release]
opt-level = 3
lto = "fat"
debug = true
